
Imports BL

Public Class SelectBills

    Public CMPNAME As String = ""
    Public BILLNO As String = ""

    Private Sub cmdcancel_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles cmdcancel.Click
        Me.Close()
    End Sub

    Private Sub cmdok_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles cmdok.Click
        Try
            BILLNO = gridrec.GetFocusedRowCellValue("SRNO")
            Me.Close()
        Catch ex As Exception
            Throw ex
        End Try
    End Sub

    Private Sub SelectBills_KeyDown(ByVal sender As Object, ByVal e As System.Windows.Forms.KeyEventArgs) Handles Me.KeyDown
        Try
            If e.KeyCode = Windows.Forms.Keys.Escape Or (e.KeyCode = Keys.X And e.Alt = True) Then
                Me.Close()
            ElseIf e.KeyCode = Keys.E And e.Alt = True Then
                cmdok_Click(sender, e)
            End If
        Catch ex As Exception
            Throw ex
        End Try
    End Sub

    Sub fillgrid(ByVal tepmcondition)
        Try
            Dim OBJCMN As New ClsCommon
            Dim dt As DataTable
            dt = OBJCMN.search(" * ", "", " (SELECT OPENINGBILL.BILL_INITIALS AS SRNO, LEDGERS.Acc_cmpname AS NAME, OPENINGBILL.BILL_AMT AS BILLAMT, OPENINGBILL.BILL_BALANCE AS BALAMT, 'OPENING' AS TYPE, OPENINGBILL.BILL_INITIALS AS REFNO, OPENINGBILL.BILL_NO AS BILLNO, OPENINGBILL.BILL_DATE AS DATE, OPENINGBILL.BILL_CMPID AS CMPID, OPENINGBILL.BILL_LOCATIONID AS LOCATIONID, OPENINGBILL.BILL_YEARID AS YEARID FROM OPENINGBILL INNER JOIN LEDGERS ON OPENINGBILL.BILL_LEDGERID = LEDGERS.Acc_id AND OPENINGBILL.BILL_CMPID = LEDGERS.Acc_cmpid AND OPENINGBILL.BILL_LOCATIONID = LEDGERS.Acc_locationid And OPENINGBILL.BILL_YEARID = LEDGERS.Acc_yearid WHERE(OPENINGBILL.BILL_BALANCE > 0) UNION ALL  SELECT INVOICEMASTER.INVOICE_INITIALS AS SRNO, LEDGERS.Acc_cmpname AS NAME, INVOICEMASTER.INVOICE_GRANDTOTAL AS BILLAMT, INVOICEMASTER.INVOICE_BALANCE AS BALAMT, 'INVOICE' AS TYPE, INVOICEMASTER.INVOICE_REFNO AS REFNO, INVOICEMASTER.INVOICE_NO AS BILLNO, INVOICEMASTER.INVOICE_DATE AS DATE, INVOICEMASTER.INVOICE_CMPID AS CMPID, INVOICEMASTER.INVOICE_LOCATIONID AS LOCATIONID, INVOICEMASTER.INVOICE_YEARID AS YEARID FROM INVOICEMASTER INNER JOIN LEDGERS ON INVOICEMASTER.INVOICE_LEDGERID = LEDGERS.Acc_id AND INVOICEMASTER.INVOICE_CMPID = LEDGERS.Acc_cmpid AND INVOICEMASTER.INVOICE_LOCATIONID = LEDGERS.Acc_locationid And INVOICEMASTER.INVOICE_YEARID = LEDGERS.Acc_yearid WHERE INVOICEMASTER.INVOICE_BALANCE > 0 UNION ALL SELECT PURCHASEMASTER.BILL_INITIALS AS SRNO, LEDGERS.Acc_cmpname AS NAME, PURCHASEMASTER.BILL_GRANDTOTAL AS BILLAMT, PURCHASEMASTER.BILL_BALANCE AS BALAMT, 'PURCHASE' AS TYPE, PURCHASEMASTER.BILL_PARTYBILLNO AS REFNO, PURCHASEMASTER.BILL_NO AS BILLNO, PURCHASEMASTER.BILL_PARTYBILLDATE AS DATE, PURCHASEMASTER.BILL_CMPID AS CMPID, PURCHASEMASTER.BILL_LOCATIONID AS LOCATIONID, PURCHASEMASTER.BILL_YEARID AS YEARID FROM PURCHASEMASTER INNER JOIN LEDGERS ON PURCHASEMASTER.BILL_LEDGERID = LEDGERS.Acc_id AND PURCHASEMASTER.BILL_CMPID = LEDGERS.Acc_cmpid AND PURCHASEMASTER.BILL_LOCATIONID = LEDGERS.Acc_locationid And PURCHASEMASTER.BILL_YEARID = LEDGERS.Acc_yearid WHERE PURCHASEMASTER.BILL_BALANCE > 0 UNION ALL SELECT NONPURCHASE.NP_INITIALS AS SRNO, LEDGERS.Acc_cmpname AS NAME, NONPURCHASE.NP_GRANDTOTAL AS BILLAMT, NONPURCHASE.NP_BALANCE AS BALAMT, 'NONPURCHASE' AS TYPE, NONPURCHASE.NP_REFNO AS REFNO, NONPURCHASE.NP_NO AS BILLNO, NONPURCHASE.NP_PARTYBILLDATE AS DATE, NONPURCHASE.NP_CMPID AS CMPID, NONPURCHASE.NP_LOCATIONID AS LOCATIONID, NONPURCHASE.NP_YEARID AS YEARID FROM NONPURCHASE INNER JOIN LEDGERS ON NONPURCHASE.NP_LEDGERID = LEDGERS.Acc_id AND NONPURCHASE.NP_CMPID = LEDGERS.Acc_cmpid AND NONPURCHASE.NP_LOCATIONID = LEDGERS.Acc_locationid And NONPURCHASE.NP_YEARID = LEDGERS.Acc_yearid WHERE NONPURCHASE.NP_BALANCE > 0) AS T ", tepmcondition & " AND T.BALAMT > 0 AND T.YEARID =" & YearId & " ORDER BY T.TYPE, T.BILLNO ")
            griddetails.DataSource = dt
        Catch ex As Exception
            Throw ex
        End Try
    End Sub

    Private Sub SelectBills_Load(ByVal sender As Object, ByVal e As System.EventArgs) Handles Me.Load
        Try
            Receipt.SELECTEDBILLNO = ""
            Dim CONDITION As String = ""
            If CMPNAME <> "" Then CONDITION = " AND T.NAME = '" & CMPNAME & "' "
            fillgrid(CONDITION)
        Catch ex As Exception
            Throw ex
        End Try
    End Sub

    Private Sub gridrec_DoubleClick(ByVal sender As Object, ByVal e As System.EventArgs) Handles gridrec.DoubleClick
        Try
            cmdok_Click(sender, e)
        Catch ex As Exception
            Throw ex
        End Try
    End Sub
End Class