
Imports BL

Public Class SelectPO

    Public FRMSTRING As String = ""
    Public PARTYNAME As String = ""
    Public PONO As Integer = 0
    Public DT As New DataTable

    Private Sub cmdexit_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles cmdexit.Click
        Me.Close()
    End Sub

    Private Sub SelectPO_KeyDown(ByVal sender As Object, ByVal e As System.Windows.Forms.KeyEventArgs) Handles Me.KeyDown
        If e.KeyCode = Windows.Forms.Keys.Escape Then
            Me.Close()
        ElseIf e.KeyCode = Keys.Enter Then
            SendKeys.Send("{Tab}")
        End If
    End Sub

    Private Sub SelectPO_Load(ByVal sender As Object, ByVal e As System.EventArgs) Handles Me.Load
        fillgrid()
    End Sub

    Sub fillgrid()
        Try
            Cursor.Current = Cursors.WaitCursor

            Dim where As String = ""
            If PONO <> 0 Then where = where & " AND PONO = " & PONO
            If PARTYNAME <> "" Then where = where & " AND NAME = '" & PARTYNAME & "'"
            Dim objclspreq As New ClsCommon()
            Dim DT As New DataTable
            If FRMSTRING = "Inwards" Then
                DT = objclspreq.search("*", "", " (SELECT PURCHASEORDER.PO_NO AS PONO, ISNULL(LEDGERS.Acc_cmpname, '') AS NAME, PURCHASEORDER.PO_DATE AS DATE, PURCHASEORDER_DESC.PO_GRIDSRNO AS GRIDSRNO, ISNULL(ITEMMASTER.item_name, '') AS ITEMNAME, '' AS QUALITY, ISNULL(PURCHASEORDER_DESC.PO_GRIDREMARKS, '') AS GRIDREMARKS, (PURCHASEORDER_DESC.PO_QTY - PURCHASEORDER_DESC.PO_RECDQTY) AS QTY, 0 AS MTRS, ISNULL(UNITMASTER.unit_abbr, '') AS UNIT, ISNULL(GROUPMASTER.group_name, '') AS GROUPNAME, ISNULL(PURCHASEORDER_DESC.PO_RATE, 0) AS RATE, ISNULL(PURCHASEORDER.PO_REFNO, '') AS ORDERNO, 'PURCHASEORDER' AS [TYPE] FROM PURCHASEORDER INNER JOIN PURCHASEORDER_DESC ON PURCHASEORDER.PO_YEARID = PURCHASEORDER_DESC.PO_YEARID AND PURCHASEORDER.PO_NO = PURCHASEORDER_DESC.PO_NO INNER JOIN LEDGERS ON PURCHASEORDER.PO_LEDGERID = LEDGERS.Acc_id INNER JOIN GROUPMASTER ON LEDGERS.Acc_groupid = GROUPMASTER.group_id LEFT OUTER JOIN UNITMASTER ON PURCHASEORDER_DESC.PO_QTYUNITID = UNITMASTER.unit_id LEFT OUTER JOIN ITEMMASTER ON PURCHASEORDER_DESC.PO_ITEMID = ITEMMASTER.item_id WHERE PURCHASEORDER_DESC.PO_CLOSED='False' AND ROUND(PURCHASEORDER_DESC.PO_QTY - PURCHASEORDER_DESC.PO_RECDQTY,2) > 0 AND PURCHASEORDER.PO_YEARID = " & YearId & " UNION ALL SELECT OPENINGPURCHASEORDER.OPO_NO AS PONO, ISNULL(LEDGERS.Acc_cmpname, '') AS NAME, OPENINGPURCHASEORDER.OPO_DATE AS DATE, OPENINGPURCHASEORDER_DESC.OPO_GRIDSRNO AS GRIDSRNO, ISNULL(ITEMMASTER.item_name, '') AS ITEMNAME, '' AS QUALITY, ISNULL(OPENINGPURCHASEORDER_DESC.OPO_GRIDREMARKS, '') AS GRIDREMARKS, (OPENINGPURCHASEORDER_DESC.OPO_QTY - OPENINGPURCHASEORDER_DESC.OPO_RECDQTY) AS QTY, 0 AS MTRS, ISNULL(UNITMASTER.unit_abbr, '') AS UNIT, ISNULL(GROUPMASTER.group_name, '') AS GROUPNAME, ISNULL(OPENINGPURCHASEORDER_DESC.OPO_RATE, 0) AS RATE, ISNULL(OPENINGPURCHASEORDER.OPO_REFNO, '') AS ORDERNO, 'OPENING' AS [TYPE] FROM OPENINGPURCHASEORDER INNER JOIN OPENINGPURCHASEORDER_DESC ON OPENINGPURCHASEORDER.OPO_YEARID = OPENINGPURCHASEORDER_DESC.OPO_YEARID AND OPENINGPURCHASEORDER.OPO_NO = OPENINGPURCHASEORDER_DESC.OPO_NO INNER JOIN LEDGERS ON OPENINGPURCHASEORDER.OPO_LEDGERID = LEDGERS.Acc_id INNER JOIN GROUPMASTER ON LEDGERS.Acc_groupid = GROUPMASTER.group_id LEFT OUTER JOIN UNITMASTER ON OPENINGPURCHASEORDER_DESC.OPO_QTYUNITID = UNITMASTER.unit_id LEFT OUTER JOIN ITEMMASTER ON OPENINGPURCHASEORDER_DESC.OPO_ITEMID = ITEMMASTER.item_id WHERE OPENINGPURCHASEORDER_DESC.OPO_CLOSED='False' AND ROUND(OPENINGPURCHASEORDER_DESC.OPO_QTY - OPENINGPURCHASEORDER_DESC.OPO_RECDQTY,2) > 0 AND OPENINGPURCHASEORDER.OPO_YEARID = " & YearId & ") AS T", where & " order by T.DATE, T.PONO")
            Else
                'FROM GREYPURCHASEORDER
                DT = objclspreq.search("*", "", " (SELECT GREYPURCHASEORDER.PO_NO AS PONO, ISNULL(LEDGERS.Acc_cmpname, '') AS NAME, GREYPURCHASEORDER.PO_DATE AS DATE, GREYPURCHASEORDER_DESC.PO_GRIDSRNO AS GRIDSRNO, ISNULL(ITEMMASTER.item_name, '') AS ITEMNAME, ISNULL(QUALITYMASTER.QUALITY_NAME,'') AS QUALITY, '' AS GRIDREMARKS, (GREYPURCHASEORDER_DESC.PO_QTY - GREYPURCHASEORDER_DESC.PO_RECDQTY) AS QTY, (GREYPURCHASEORDER_DESC.PO_MTRS - GREYPURCHASEORDER_DESC.PO_RECDMTRS) AS MTRS, ISNULL(UNITMASTER.unit_abbr, '') AS UNIT, ISNULL(GROUPMASTER.group_name, '') AS GROUPNAME, ISNULL(GREYPURCHASEORDER_DESC.PO_RATE, 0) AS RATE, ISNULL(GREYPURCHASEORDER.PO_REFNO, '') AS ORDERNO, 'GREYPURCHASEORDER' AS [TYPE] FROM GREYPURCHASEORDER INNER JOIN GREYPURCHASEORDER_DESC ON GREYPURCHASEORDER.PO_YEARID = GREYPURCHASEORDER_DESC.PO_YEARID AND GREYPURCHASEORDER.PO_NO = GREYPURCHASEORDER_DESC.PO_NO INNER JOIN LEDGERS ON GREYPURCHASEORDER.PO_LEDGERID = LEDGERS.Acc_id INNER JOIN GROUPMASTER ON LEDGERS.Acc_groupid = GROUPMASTER.group_id LEFT OUTER JOIN UNITMASTER ON GREYPURCHASEORDER_DESC.PO_QTYUNITID = UNITMASTER.unit_id LEFT OUTER JOIN ITEMMASTER ON GREYPURCHASEORDER_DESC.PO_ITEMID = ITEMMASTER.item_id INNER JOIN QUALITYMASTER ON GREYPURCHASEORDER_DESC.PO_QUALITYID = QUALITYMASTER.QUALITY_ID WHERE GREYPURCHASEORDER_DESC.PO_CLOSED='False' AND ROUND(GREYPURCHASEORDER_DESC.PO_QTY - GREYPURCHASEORDER_DESC.PO_RECDQTY,2) > 0 AND GREYPURCHASEORDER.PO_YEARID = " & YearId & " UNION ALL SELECT OPENINGGREYPURCHASEORDER.OPO_NO AS PONO, ISNULL(LEDGERS.Acc_cmpname, '') AS NAME, OPENINGGREYPURCHASEORDER.OPO_DATE AS DATE, OPENINGGREYPURCHASEORDER_DESC.OPO_GRIDSRNO AS GRIDSRNO, ISNULL(ITEMMASTER.item_name, '') AS ITEMNAME, ISNULL(QUALITYMASTER.QUALITY_NAME,'') AS QUALITY, '' AS GRIDREMARKS, (OPENINGGREYPURCHASEORDER_DESC.OPO_QTY - OPENINGGREYPURCHASEORDER_DESC.OPO_RECDQTY) AS QTY, (OPENINGGREYPURCHASEORDER_DESC.OPO_MTRS - OPENINGGREYPURCHASEORDER_DESC.OPO_RECDMTRS) AS MTRS, ISNULL(UNITMASTER.unit_abbr, '') AS UNIT, ISNULL(GROUPMASTER.group_name, '') AS GROUPNAME, ISNULL(OPENINGGREYPURCHASEORDER_DESC.OPO_RATE, 0) AS RATE, ISNULL(OPENINGGREYPURCHASEORDER.OPO_REFNO, '') AS ORDERNO, 'OPENINGGREY' AS [TYPE] FROM OPENINGGREYPURCHASEORDER INNER JOIN OPENINGGREYPURCHASEORDER_DESC ON OPENINGGREYPURCHASEORDER.OPO_YEARID = OPENINGGREYPURCHASEORDER_DESC.OPO_YEARID AND OPENINGGREYPURCHASEORDER.OPO_NO = OPENINGGREYPURCHASEORDER_DESC.OPO_NO INNER JOIN LEDGERS ON OPENINGGREYPURCHASEORDER.OPO_LEDGERID = LEDGERS.Acc_id INNER JOIN GROUPMASTER ON LEDGERS.Acc_groupid = GROUPMASTER.group_id LEFT OUTER JOIN UNITMASTER ON OPENINGGREYPURCHASEORDER_DESC.OPO_QTYUNITID = UNITMASTER.unit_id LEFT OUTER JOIN ITEMMASTER ON OPENINGGREYPURCHASEORDER_DESC.OPO_ITEMID = ITEMMASTER.item_id INNER JOIN QUALITYMASTER ON OPENINGGREYPURCHASEORDER_DESC.OPO_QUALITYID = QUALITYMASTER.QUALITY_ID WHERE OPENINGGREYPURCHASEORDER_DESC.OPO_CLOSED='False' AND ROUND(OPENINGGREYPURCHASEORDER_DESC.OPO_QTY - OPENINGGREYPURCHASEORDER_DESC.OPO_RECDQTY,2) > 0 AND OPENINGGREYPURCHASEORDER.OPO_YEARID = " & YearId & ") AS T", where & " order by T.DATE, T.PONO")
            End If
            gridbilldetails.DataSource = DT
            If dt.Rows.Count > 0 Then
                gridbill.FocusedRowHandle = gridbill.RowCount - 1
                gridbill.TopRowIndex = gridbill.RowCount - 15
            End If
        Catch ex As Exception
            If ErrHandle(ex.Message.GetHashCode) = False Then Throw ex
        Finally
            Cursor.Current = Cursors.Default

        End Try
    End Sub

    Private Sub cmdok_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles cmdok.Click
        Try

            DT.Columns.Add("PONO")
            DT.Columns.Add("NAME")
            DT.Columns.Add("PODATE")
            DT.Columns.Add("GRIDSRNO")
            DT.Columns.Add("ITEMNAME")
            DT.Columns.Add("QUALITY")
            DT.Columns.Add("QTY")
            DT.Columns.Add("MTRS")
            DT.Columns.Add("GROUPNAME")
            DT.Columns.Add("RATE")
            DT.Columns.Add("TYPE")

            Dim SELECTEDROWS As Int32() = gridbill.GetSelectedRows()
            For I As Integer = 0 To Val(SELECTEDROWS.Length - 1)
                Dim dtrow As DataRow = gridbill.GetDataRow(SELECTEDROWS(I))
                DT.Rows.Add(dtrow("PONO"), dtrow("NAME"), dtrow("DATE"), Val(dtrow("GRIDSRNO")), dtrow("ITEMNAME"), dtrow("QUALITY"), Val(dtrow("QTY")), Val(dtrow("MTRS")), dtrow("GROUPNAME"), Val(dtrow("RATE")), dtrow("TYPE"))
            Next
            Me.Close()

        Catch ex As Exception
            If ErrHandle(ex.Message.GetHashCode) = False Then Throw ex
        End Try
    End Sub

    Private Sub gridquotation_CellDoubleClick(ByVal sender As Object, ByVal e As System.Windows.Forms.DataGridViewCellEventArgs)
        Try
            cmdok_Click(sender, e)
        Catch ex As Exception
            If ErrHandle(ex.Message.GetHashCode) = False Then Throw ex
        End Try
    End Sub

    Private Sub SelectPO_Shown(sender As Object, e As EventArgs) Handles Me.Shown
        Try
            If FRMSTRING = "Inwards" Then
                GQUALITY.Visible = False
                GMTRS.Visible = False
            Else
                GITEM.Visible = False
                GGRIDREMARKS.Visible = False
            End If
        Catch ex As Exception
            Throw ex
        End Try
    End Sub
End Class