
Imports BL
Imports System.Windows.Forms
Imports DevExpress.XtraGrid.Views.Grid

Public Class GreyPurchaseOrderClose

    Dim USERADD, USEREDIT, USERVIEW, USERDELETE As Boolean      'USED FOR RIGHT MANAGEMAENT

    Private Sub cmdexit_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles cmdexit.Click
        Me.Close()
    End Sub

    Private Sub PurchaseOrderClose_KeyDown(ByVal sender As Object, ByVal e As System.Windows.Forms.KeyEventArgs) Handles Me.KeyDown
        Try
            If e.KeyCode = Windows.Forms.Keys.Escape Then
                Me.Close()
            ElseIf e.KeyCode = Keys.Space And e.Control = True Then
                'SELECT ALL DATA
                For i As Integer = 0 To gridbill.RowCount - 1
                    Dim dtrow As DataRow = gridbill.GetDataRow(i)
                    dtrow("CLOSED") = Not Convert.ToBoolean(dtrow("CLOSED"))
                Next
            End If
        Catch ex As Exception
            If ErrHandle(ex.Message.GetHashCode) = False Then Throw ex
        End Try
    End Sub

    Private Sub PurchaseOrderClose_Load(ByVal sender As Object, ByVal e As System.EventArgs) Handles Me.Load
        Try
            Dim DTROW() As DataRow
            DTROW = USERRIGHTS.Select("FormName = 'PURCHASE ORDER'")
            USERADD = DTROW(0).Item(1)
            USEREDIT = DTROW(0).Item(2)
            USERVIEW = DTROW(0).Item(3)
            USERDELETE = DTROW(0).Item(4)

            If USEREDIT = False And USERVIEW = False Then
                MsgBox("Insufficient Rights")
                Exit Sub
            End If
            fillgrid("")
        Catch ex As Exception
            Throw ex
        End Try
    End Sub

    Sub fillgrid(ByVal TEMPCONDITION)
        Try
            Dim objclsCMST As New ClsCommonMaster
            Dim dt As New DataTable
            If RBPENDING.Checked = True Then
                dt = objclsCMST.search("*", "", " (SELECT  GREYPURCHASEORDER.PO_NO AS PONO, GREYPURCHASEORDER.PO_DATE AS PODATE, GREYPURCHASEORDER.PO_DUEDATE AS DUEDATE, LEDGERS.Acc_cmpname AS NAME, ISNULL(GREYPURCHASEORDER.PO_CRDAYS, 0) AS CRDAYS,ISNULL(GREYPURCHASEORDER.PO_DELDAYS, 0) AS DELDAYS, ISNULL(GREYPURCHASEORDER.PO_REFNO, '0') AS REFNO, ISNULL(GREYPURCHASEORDER.PO_REMARKS, '') AS REMARKS, ISNULL(GREYPURCHASEORDER.PO_DONE, 0) AS PODONE, GREYPURCHASEORDER_DESC.PO_GRIDSRNO AS POGRIDSRNO, ISNULL(ITEMMASTER.item_name, '') AS ITEMNAME, ISNULL(QUALITYMASTER.QUALITY_name, '') AS QUALITY, ISNULL(GREYPURCHASEORDER_DESC.PO_QTY, 0) AS QTY, ISNULL(GREYPURCHASEORDER_DESC.PO_MTRS, 0) AS MTRS, ISNULL(GREYPURCHASEORDER_DESC.PO_RATE, 0) AS RATE, ISNULL(GREYPURCHASEORDER_DESC.PO_RECDQTY, 0) AS RECDPCS,ISNULL(GREYPURCHASEORDER_DESC.PO_RECDMTRS, 0) AS RECDMTRS, ISNULL(GREYPURCHASEORDER_DESC.PO_DONE, 0) AS GRIDPODONE, ISNULL(BROKERLEDGERS.Acc_cmpname, '') AS BROKER,ISNULL(GREYPURCHASEORDER.PO_ORDERTYPE, '') AS ORDERTYPE, ISNULL(GREYPURCHASEORDER_DESC.PO_CLOSED, 0) AS CLOSED, GREYPURCHASEORDER_DESC.PO_QTY - GREYPURCHASEORDER_DESC.PO_RECDQTY AS BALPCS, GREYPURCHASEORDER_DESC.PO_MTRS - GREYPURCHASEORDER_DESC.PO_RECDMTRS AS BALMTRS, 'GREYPURCHASEORDER' AS TYPE FROM  GREYPURCHASEORDER INNER JOIN GREYPURCHASEORDER_DESC ON GREYPURCHASEORDER.PO_NO = GREYPURCHASEORDER_DESC.PO_NO AND GREYPURCHASEORDER.PO_YEARID = GREYPURCHASEORDER_DESC.PO_YEARID INNER JOIN ITEMMASTER ON GREYPURCHASEORDER_DESC.PO_ITEMID = ITEMMASTER.item_id LEFT OUTER JOIN LEDGERS AS BROKERLEDGERS ON GREYPURCHASEORDER.PO_BROKERID = BROKERLEDGERS.Acc_id INNER JOIN LEDGERS ON GREYPURCHASEORDER.PO_LEDGERID = LEDGERS.Acc_id LEFT OUTER JOIN QUALITYMASTER ON GREYPURCHASEORDER_DESC.PO_QUALITYID = QUALITYMASTER.QUALITY_id WHERE GREYPURCHASEORDER_DESC.PO_CLOSED = 'FALSE' and (GREYPURCHASEORDER_DESC.PO_QTY-GREYPURCHASEORDER_DESC.PO_RECDQTY)>0 AND dbo.GREYPURCHASEORDER.PO_yearid=" & YearId & " UNION ALL SELECT  OPENINGGREYPURCHASEORDER.OPO_NO AS PONO, OPENINGGREYPURCHASEORDER.OPO_DATE AS PODATE, OPENINGGREYPURCHASEORDER.OPO_DUEDATE AS DUEDATE, LEDGERS.Acc_cmpname AS NAME,ISNULL(OPENINGGREYPURCHASEORDER.OPO_CRDAYS, 0) AS CRDAYS, ISNULL(OPENINGGREYPURCHASEORDER.OPO_DELDAYS, 0) AS DELDAYS, ISNULL(OPENINGGREYPURCHASEORDER.OPO_REFNO, '0') AS REFNO,ISNULL(OPENINGGREYPURCHASEORDER.OPO_REMARKS, '') AS REMARKS, ISNULL(OPENINGGREYPURCHASEORDER.OPO_DONE, 0) AS PODONE, OPENINGGREYPURCHASEORDER_DESC.OPO_GRIDSRNO AS POGRIDSRNO,ISNULL(ITEMMASTER.item_name, '') AS ITEMNAME, ISNULL(QUALITYMASTER.QUALITY_name, '') AS QUALITY, ISNULL(OPENINGGREYPURCHASEORDER_DESC.OPO_QTY, 0) AS QTY,ISNULL(OPENINGGREYPURCHASEORDER_DESC.OPO_MTRS, 0) AS MTRS, ISNULL(OPENINGGREYPURCHASEORDER_DESC.OPO_RATE, 0) AS RATE, ISNULL(OPENINGGREYPURCHASEORDER_DESC.OPO_RECDQTY, 0) AS RECDQTY,ISNULL(OPENINGGREYPURCHASEORDER_DESC.OPO_RECDMTRS, 0) AS RECDMTRS, ISNULL(OPENINGGREYPURCHASEORDER_DESC.OPO_DONE, 0) AS GRIDPODONE, ISNULL(BROKERLEDGERS.Acc_cmpname, '') AS BROKER,ISNULL(OPENINGGREYPURCHASEORDER.OPO_ORDERTYPE, '') AS ORDERTYPE, ISNULL(OPENINGGREYPURCHASEORDER_DESC.OPO_CLOSED, 0) AS CLOSED,OPENINGGREYPURCHASEORDER_DESC.OPO_QTY - OPENINGGREYPURCHASEORDER_DESC.OPO_RECDQTY AS BALPCS,OPENINGGREYPURCHASEORDER_DESC.OPO_MTRS - OPENINGGREYPURCHASEORDER_DESC.OPO_RECDMTRS AS BALMTRS, 'OPENINGGREY' AS TYPE FROM OPENINGGREYPURCHASEORDER INNER JOIN OPENINGGREYPURCHASEORDER_DESC ON OPENINGGREYPURCHASEORDER.OPO_NO = OPENINGGREYPURCHASEORDER_DESC.OPO_NO AND OPENINGGREYPURCHASEORDER.OPO_YEARID = OPENINGGREYPURCHASEORDER_DESC.OPO_YEARID INNER JOIN ITEMMASTER ON OPENINGGREYPURCHASEORDER_DESC.OPO_ITEMID = ITEMMASTER.item_id LEFT OUTER JOIN LEDGERS AS BROKERLEDGERS ON OPENINGGREYPURCHASEORDER.OPO_BROKERID = BROKERLEDGERS.Acc_id INNER JOIN LEDGERS ON OPENINGGREYPURCHASEORDER.OPO_LEDGERID = LEDGERS.Acc_id LEFT OUTER JOIN QUALITYMASTER ON OPENINGGREYPURCHASEORDER_DESC.OPO_QUALITYID = QUALITYMASTER.QUALITY_id WHERE OPENINGGREYPURCHASEORDER_DESC.OPO_CLOSED = 'FALSE' and (OPENINGGREYPURCHASEORDER_DESC.OPO_QTY-OPENINGGREYPURCHASEORDER_DESC.OPO_RECDQTY)>0 AND dbo.OPENINGGREYPURCHASEORDER.OPO_yearid=" & YearId & ") AS T", " ORDER BY PONO, POGRIDSRNO")
            Else
                dt = objclsCMST.search("*", "", " (SELECT  GREYPURCHASEORDER.PO_NO AS PONO, GREYPURCHASEORDER.PO_DATE AS PODATE, GREYPURCHASEORDER.PO_DUEDATE AS DUEDATE, LEDGERS.Acc_cmpname AS NAME, ISNULL(GREYPURCHASEORDER.PO_CRDAYS, 0) AS CRDAYS,ISNULL(GREYPURCHASEORDER.PO_DELDAYS, 0) AS DELDAYS, ISNULL(GREYPURCHASEORDER.PO_REFNO, '0') AS REFNO, ISNULL(GREYPURCHASEORDER.PO_REMARKS, '') AS REMARKS, ISNULL(GREYPURCHASEORDER.PO_DONE, 0) AS PODONE, GREYPURCHASEORDER_DESC.PO_GRIDSRNO AS POGRIDSRNO, ISNULL(ITEMMASTER.item_name, '') AS ITEMNAME, ISNULL(QUALITYMASTER.QUALITY_name, '') AS QUALITY, ISNULL(GREYPURCHASEORDER_DESC.PO_QTY, 0) AS QTY, ISNULL(GREYPURCHASEORDER_DESC.PO_MTRS, 0) AS MTRS, ISNULL(GREYPURCHASEORDER_DESC.PO_RATE, 0) AS RATE, ISNULL(GREYPURCHASEORDER_DESC.PO_RECDQTY, 0) AS RECDPCS,ISNULL(GREYPURCHASEORDER_DESC.PO_RECDMTRS, 0) AS RECDMTRS, ISNULL(GREYPURCHASEORDER_DESC.PO_DONE, 0) AS GRIDPODONE, ISNULL(BROKERLEDGERS.Acc_cmpname, '') AS BROKER,ISNULL(GREYPURCHASEORDER.PO_ORDERTYPE, '') AS ORDERTYPE, ISNULL(GREYPURCHASEORDER_DESC.PO_CLOSED, 0) AS CLOSED, GREYPURCHASEORDER_DESC.PO_QTY - GREYPURCHASEORDER_DESC.PO_RECDQTY AS BALPCS, GREYPURCHASEORDER_DESC.PO_MTRS - GREYPURCHASEORDER_DESC.PO_RECDMTRS AS BALMTRS, 'GREYPURCHASEORDER' AS TYPE FROM  GREYPURCHASEORDER INNER JOIN GREYPURCHASEORDER_DESC ON GREYPURCHASEORDER.PO_NO = GREYPURCHASEORDER_DESC.PO_NO AND GREYPURCHASEORDER.PO_YEARID = GREYPURCHASEORDER_DESC.PO_YEARID INNER JOIN ITEMMASTER ON GREYPURCHASEORDER_DESC.PO_ITEMID = ITEMMASTER.item_id LEFT OUTER JOIN LEDGERS AS BROKERLEDGERS ON GREYPURCHASEORDER.PO_BROKERID = BROKERLEDGERS.Acc_id INNER JOIN LEDGERS ON GREYPURCHASEORDER.PO_LEDGERID = LEDGERS.Acc_id LEFT OUTER JOIN QUALITYMASTER ON GREYPURCHASEORDER_DESC.PO_QUALITYID = QUALITYMASTER.QUALITY_id WHERE GREYPURCHASEORDER_DESC.PO_CLOSED = 'TRUE' and (GREYPURCHASEORDER_DESC.PO_QTY-GREYPURCHASEORDER_DESC.PO_RECDQTY)>0 AND dbo.GREYPURCHASEORDER.PO_yearid=" & YearId & " UNION ALL SELECT  OPENINGGREYPURCHASEORDER.OPO_NO AS PONO, OPENINGGREYPURCHASEORDER.OPO_DATE AS PODATE, OPENINGGREYPURCHASEORDER.OPO_DUEDATE AS DUEDATE, LEDGERS.Acc_cmpname AS NAME,ISNULL(OPENINGGREYPURCHASEORDER.OPO_CRDAYS, 0) AS CRDAYS, ISNULL(OPENINGGREYPURCHASEORDER.OPO_DELDAYS, 0) AS DELDAYS, ISNULL(OPENINGGREYPURCHASEORDER.OPO_REFNO, '0') AS REFNO,ISNULL(OPENINGGREYPURCHASEORDER.OPO_REMARKS, '') AS REMARKS, ISNULL(OPENINGGREYPURCHASEORDER.OPO_DONE, 0) AS PODONE, OPENINGGREYPURCHASEORDER_DESC.OPO_GRIDSRNO AS POGRIDSRNO,ISNULL(ITEMMASTER.item_name, '') AS ITEMNAME, ISNULL(QUALITYMASTER.QUALITY_name, '') AS QUALITY, ISNULL(OPENINGGREYPURCHASEORDER_DESC.OPO_QTY, 0) AS QTY,ISNULL(OPENINGGREYPURCHASEORDER_DESC.OPO_MTRS, 0) AS MTRS, ISNULL(OPENINGGREYPURCHASEORDER_DESC.OPO_RATE, 0) AS RATE, ISNULL(OPENINGGREYPURCHASEORDER_DESC.OPO_RECDQTY, 0) AS RECDQTY,ISNULL(OPENINGGREYPURCHASEORDER_DESC.OPO_RECDMTRS, 0) AS RECDMTRS, ISNULL(OPENINGGREYPURCHASEORDER_DESC.OPO_DONE, 0) AS GRIDPODONE, ISNULL(BROKERLEDGERS.Acc_cmpname, '') AS BROKER,ISNULL(OPENINGGREYPURCHASEORDER.OPO_ORDERTYPE, '') AS ORDERTYPE, ISNULL(OPENINGGREYPURCHASEORDER_DESC.OPO_CLOSED, 0) AS CLOSED,OPENINGGREYPURCHASEORDER_DESC.OPO_QTY - OPENINGGREYPURCHASEORDER_DESC.OPO_RECDQTY AS BALPCS,OPENINGGREYPURCHASEORDER_DESC.OPO_MTRS - OPENINGGREYPURCHASEORDER_DESC.OPO_RECDMTRS AS BALMTRS, 'OPENINGGREY' AS TYPE FROM OPENINGGREYPURCHASEORDER INNER JOIN OPENINGGREYPURCHASEORDER_DESC ON OPENINGGREYPURCHASEORDER.OPO_NO = OPENINGGREYPURCHASEORDER_DESC.OPO_NO AND OPENINGGREYPURCHASEORDER.OPO_YEARID = OPENINGGREYPURCHASEORDER_DESC.OPO_YEARID INNER JOIN ITEMMASTER ON OPENINGGREYPURCHASEORDER_DESC.OPO_ITEMID = ITEMMASTER.item_id LEFT OUTER JOIN LEDGERS AS BROKERLEDGERS ON OPENINGGREYPURCHASEORDER.OPO_BROKERID = BROKERLEDGERS.Acc_id INNER JOIN LEDGERS ON OPENINGGREYPURCHASEORDER.OPO_LEDGERID = LEDGERS.Acc_id LEFT OUTER JOIN QUALITYMASTER ON OPENINGGREYPURCHASEORDER_DESC.OPO_QUALITYID = QUALITYMASTER.QUALITY_id WHERE OPENINGGREYPURCHASEORDER_DESC.OPO_CLOSED = 'TRUE' and (OPENINGGREYPURCHASEORDER_DESC.OPO_QTY-OPENINGGREYPURCHASEORDER_DESC.OPO_RECDQTY)>0 AND dbo.OPENINGGREYPURCHASEORDER.OPO_yearid=" & YearId & ") AS T", " ORDER BY PONO, POGRIDSRNO")
            End If
            gridbilldetails.DataSource = dt
            If dt.Rows.Count > 0 Then
                gridbill.FocusedRowHandle = gridbill.RowCount - 1
                gridbill.TopRowIndex = gridbill.RowCount - 15
            End If
        Catch ex As Exception
            Throw ex
        End Try
    End Sub

    Private Sub cmdok_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles cmdok.Click
        Try

            If RBENTERED.Checked = True Then
                If MsgBox("You have trying to Re-Open Closed Orders, Wish to Proceed?", MsgBoxStyle.YesNo) = MsgBoxResult.No Then Exit Sub
            End If

            Dim OBJCMN As New ClsCommon
            For I As Integer = 0 To gridbill.RowCount - 1
                Dim DTROW As DataRow = gridbill.GetDataRow(I)
                If RBPENDING.Checked = True Then
                    If Convert.ToBoolean(DTROW("CLOSED")) = True Then
                        If DTROW("TYPE") = "GREYPURCHASEORDER" Then Dim DT As DataTable = OBJCMN.Execute_Any_String("UPDATE GREYPURCHASEORDER_DESC SET PO_CLOSED = 1 WHERE PO_NO = " & Val(DTROW("PONO")) & " AND PO_GRIDSRNO = " & Val(DTROW("POGRIDSRNO")) & " AND PO_YEARID = " & YearId, "", "") Else Dim DT As DataTable = OBJCMN.Execute_Any_String("UPDATE OPENINGGREYPURCHASEORDER_DESC SET OPO_CLOSED = 1 WHERE OPO_NO = " & Val(DTROW("PONO")) & " AND OPO_GRIDSRNO = " & Val(DTROW("POGRIDSRNO")) & " AND OPO_YEARID = " & YearId, "", "")
                    End If
                Else
                    If Convert.ToBoolean(DTROW("CLOSED")) = True Then
                        If DTROW("TYPE") = "GREYPURCHASEORDER" Then Dim DT As DataTable = OBJCMN.Execute_Any_String("UPDATE GREYPURCHASEORDER_DESC SET PO_CLOSED = 0 WHERE PO_NO = " & Val(DTROW("PONO")) & " AND PO_GRIDSRNO = " & Val(DTROW("POGRIDSRNO")) & " AND PO_YEARID = " & YearId, "", "") Else Dim DT As DataTable = OBJCMN.Execute_Any_String("UPDATE OPENINGGREYPURCHASEORDER_DESC SET OPO_CLOSED = 0 WHERE OPO_NO = " & Val(DTROW("PONO")) & " AND OPO_GRIDSRNO = " & Val(DTROW("POGRIDSRNO")) & " AND OPO_YEARID = " & YearId, "", "")
                    End If
                End If

            Next
            MsgBox("Entries Updated")
            fillgrid("")
        Catch ex As Exception
            Throw ex
        End Try
    End Sub

    Private Sub CMDREFRESH_Click(sender As Object, e As EventArgs) Handles CMDREFRESH.Click
        Try
            fillgrid("")
        Catch ex As Exception
            Throw ex
        End Try
    End Sub

    Private Sub gridbill_RowStyle(ByVal sender As Object, ByVal e As DevExpress.XtraGrid.Views.Grid.RowStyleEventArgs) Handles gridbill.RowStyle
        Try
            If e.RowHandle >= 0 Then
                Dim View As GridView = sender
                If View.GetRowCellDisplayText(e.RowHandle, View.Columns("CLOSED")) = "Checked" Then
                    e.Appearance.Font = New System.Drawing.Font("CALIBRI", 9.0F, System.Drawing.FontStyle.Bold)
                    e.Appearance.BackColor = Color.Yellow
                End If
            End If
        Catch ex As Exception
            Throw ex
        End Try
    End Sub

    Private Sub PrintToolStripButton_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles PrintToolStripButton.Click
        Try

            Dim PATH As String = Application.StartupPath & "\Purchase Order Details.XLS"
            Dim opti As New DevExpress.XtraPrinting.XlsExportOptions
            opti.ShowGridLines = True
            opti.SheetName = "Purchase Order Details"
            gridbill.ExportToXls(PATH, opti)
            EXCELCMPHEADER(PATH, "Purchase Order Details", gridbill.VisibleColumns.Count + gridbill.GroupCount)
        Catch ex As Exception
            MsgBox("Purchase Order Details Excel File is Open, Please Close the File first then try to Export", MsgBoxStyle.Critical)
        End Try
    End Sub

    Private Sub CHKSELECTALL_CheckedChanged(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles CHKSELECTALL.CheckedChanged
        Try
            If gridbilldetails.Visible = True Then
                For i As Integer = 0 To gridbill.RowCount - 1
                    Dim dtrow As DataRow = gridbill.GetDataRow(i)
                    dtrow("CLOSED") = CHKSELECTALL.Checked
                Next
            End If
        Catch ex As Exception
            Throw ex
        End Try
    End Sub

    Private Sub gridbill_KeyDown(sender As Object, e As KeyEventArgs) Handles gridbill.KeyDown
        Try
            If e.KeyCode = Keys.Space Then
                Dim dtrow As DataRow = gridbill.GetFocusedDataRow()
                dtrow("CLOSED") = Not dtrow("CLOSED")
            End If
        Catch ex As Exception
            Throw ex
        End Try
    End Sub

End Class